name: Bongothy
version: '${version}'
main: bongothy.PluginMain
api-version: 1.21
commands:
  sethome:
    description: Set your home location.
    usage: /sethome
    permission: bongothy.sethome
  home:
      description: Teleport to your home location.
      usage: /home
      permission: bongothy.home
permissions:
  bongothy.sethome:
    description: Allows the player to set their home location.
    default: true
  bongothy.home:
    description: Allows the player to teleport to their home location.
    default: true